// allKeys.json
const allKeys = {
    "intro": {},
    "intro_name": "Name",
    "intro_email": "E-Mail",
    "intro_role": "Your relationship with Reverie",
    "partnerStepOne_deliveryExpectationRating": "How well has Reverie been able to deliver as per your expectations from the partnership? ",
    "partnerStepOne_reduceTat": "How well did our products/solutions help you reduce the time to launch your product/service? ",
    "partnerStepOne_deliveryTimeline": "Has the Reverie team been able to deliver the product/solution as per your expectations and within agreed timelines?",
    "partnerStepOne_solutionEffectiveness": "Please rate the effectiveness of our solutions in resolving your client needs &amp; problems",
    "partnerStepOne_partnerClientResponse": "Did we support you effectively to engage with clients &amp; provide a faster response than your usual sales cycle?",
    "partnerStepOne_trainingBenefits": "Does our training help you in mapping the right solution for different use cases?",
    "partnerStepOne_collateralRelevance": "Have we provided you relevant collaterals &amp; effective demos to ensure sales effectiveness in building a better sales pipeline?",
    "partnerStepOne_engagementWithPartnerTeam": "Please rate our engagement with your team in effectively working on opportunities &amp; pipeline.",
    "partnerStepOne_industryInsights": "Insights related to the Industry",
    "partnerStepOne_queryResponsiveness": "Responsiveness to your queries",
    "partnerStepOne_domainExpertise": "Domain Expertise",
    "partnerStepOne_technicalCompetency": "Technical Competency",
    "partnerStepOne_reveriePortfolioEffectiveness": "How effective has Reverie’s portfolio been in helping you offer a complete package of products/solutions to your clients?",
    "partnerStepOne_productPositiveImpact": "Please rate the positive impact our products/solutions have on your clients?",
    "partnerStepOne_reveriePartnerPipelineContribution": "Has Reverie helped you in opening new doors and increasing your pipeline?",
    "partnerStepOne_partnerSupportWinProject": "Did our partnership and support help you in winning projects ?",
    "partnerStepOne_chooseReverieForRequirements": "How likely are you to choose Reverie for any Language localization requirements for your clients? ",
    "partnerStepOne_comprehensiveAndInnovative": "Do you agree that Reverie offers the most comprehensive and innovative product portfolio related to Indian languages ?",
    "partnerStepOne_topThree": "Would you consider Reverie as one of the Top-3 companies among language technology businesses in India?",
    "partnerStepOne_additionalComment": "Please share any additional comments/suggestions:",
    "customerStepOne_deliveryExpectationRating": "How effectively has Reverie been able to deliver as per your expectations? ",
    "customerStepOne_gtmTat": "How well did we help you in reducing the time to launch your product/service?",
    "customerStepOne_deliveryTimeline": "Has our team been able to deliver the product/solution as per your expectations and within agreed timelines?",
    "customerStepOne_solutionEffectiveness": "Please rate the effectiveness of our solutions in resolving your problems",
    "customerStepOne_deliverySkills": "Skill in delivering solutions",
    "customerStepOne_queryResponsiveness": "Responsiveness to your queries",
    "customerStepOne_domainExpertise": "Domain Expertise",
    "customerStepOne_engagementEffectiveness": "Effectiveness of the engagement",
    "customerStepOne_achieveInitialObjective": "How well did Reverie help you achieve your initial objectives for the localization project?   ",
    "customerStepOne_referalPossibility": "How likely are you to refer Reverie to other companies looking for language localization requirements?",
    "customerStepOne_problemApproachability": "Do you agree that you will approach Reverie first for solutions to your critical problems related to language localization?",
    "customerStepOne_innovativeness": "How comprehensive and innovative are Reverie’s products related to Indian languages?",
    "customerStepOne_languageBestPractice": "How effectively does Reverie help your business by sharing best practices related to languages?",
    "customerStepOne_topThree": "Would you consider Reverie as one of the Top-3 companies among the language technology businesses in India?",
    "customerStepTwo_tsInteract": "Have you experienced our translation services?",
    "customerStepTwo_translationQuality": "Quality of translation:",
    "customerStepTwo_translationTat": "Time taken for translation:",
    "customerStepThree_techInteract": "Have you had any interaction with our technical team? ",
    "customerStepThree_techTeamEffectiveness": "How effective was our technical team in solving your problem? ",
    "customerStepThree_techTeamQueryResolve": "How efficient was the technical team in solving your queries on time?",
    "customerStepThree_techSkillsForDelivery": "Technical Skills in delivering the solution",
    "customerStepThree_sme": "Subject Matter Expertise",
    "customerStepThree_additionalComment": "Please share any additional comments/suggestions:"
}

module.exports = allKeys;